'use strict';
const bodies=JSON.parse(document.querySelector('#data').textContent),canvas=document.querySelector('#space'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);let selected=bodies[2],days=0,paused=false,speed=5,zoom=1,tilt=.57,track=false,focus=false,last=performance.now(),points=[];
const layers={'Orbits':true,'Labels':true,'Asteroid belt':true,'Grid':true};
let seed=3837;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const stars=Array.from({length:650},()=>[random(),random(),random()]);const belt=Array.from({length:550},()=>[random()*Math.PI*2,4.55+random()*.55,random()]);
function log(text){$('event').textContent=text}
function select(body){selected=body;document.querySelectorAll('.body').forEach(b=>b.classList.toggle('active',b.dataset.name===body.name));$('name').textContent=body.name;$('planet-icon').style.background=`radial-gradient(circle at 30% 25%,#e9f9ff,${body.color} 40%,#06111d 85%)`;$('facts').innerHTML=[['Radius',`${body.radius.toLocaleString()} km`],['Mean distance',`${body.au.toFixed(3)} AU`],['Orbital period',`${body.period.toLocaleString()} days`],['Model','Circular / coplanar']].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');log(`${body.name} selected · telemetry updated`)}
document.querySelectorAll('.body').forEach(b=>b.onclick=()=>select(bodies.find(p=>p.name===b.dataset.name)));
document.querySelectorAll('[data-layer]').forEach(b=>b.onchange=()=>layers[b.dataset.layer]=b.checked);
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶ RESUME':'Ⅱ PAUSE';log(paused?'Simulation paused':'Simulation resumed')};$('speed').onchange=e=>speed=Number(e.target.value);
$('in').onclick=()=>zoom=Math.min(zoom*1.2,3);$('out').onclick=()=>zoom=Math.max(zoom/1.2,.5);
function reset(){zoom=1;focus=false;track=false;$('track').classList.remove('active');$('focus').classList.remove('active')}
$('reset').onclick=reset;$('home').onclick=()=>{reset();tilt=.57};$('top').onclick=()=>{tilt=tilt===1?.57:1;$('top').classList.toggle('active',tilt===1)};
$('focus').onclick=()=>{focus=!focus;$('focus').classList.toggle('active',focus)};$('track').onclick=()=>{track=!track;$('track').classList.toggle('active',track)};
$('export').onclick=()=>{const data={model:'Idealized circular orbit simulation',days,bodies:bodies.map(b=>{let a=b.phase+days/b.period*Math.PI*2;return{name:b.name,x_au:b.au*Math.cos(a),y_au:b.au*Math.sin(a)}})};let url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download='orbital-telemetry.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);log('Telemetry snapshot exported')};
canvas.onclick=e=>{let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let p=points.find(p=>Math.hypot(p.x-x,p.y-y)<Math.max(p.size,17));if(p)select(p.body)};
function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;if(!paused)days+=dt*speed;const r=canvas.getBoundingClientRect(),w=r.width,h=r.height,dpr=devicePixelRatio||1;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);stars.forEach(([x,y,s])=>{ctx.fillStyle=`rgba(140,195,232,${.12+s*.65})`;ctx.fillRect(x*w,y*h,s> .96?2:1,s>.96?2:1)});
const unit=Math.min(w/19,h/(19*tilt))*zoom;let cx=w*.5,cy=h*.55;const selectedIndex=bodies.indexOf(selected),a=selected.phase+days/selected.period*Math.PI*2;if(focus){cx-=Math.cos(a)*(selectedIndex+1.5)*unit;cy-=Math.sin(a)*(selectedIndex+1.5)*unit*tilt}
if(layers.Grid){ctx.strokeStyle='#12304666';ctx.lineWidth=.5;for(let x=0;x<w;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}
if(layers['Asteroid belt'])belt.forEach(([a,r,s])=>{ctx.fillStyle=`rgba(211,164,106,${s*.65})`;ctx.fillRect(cx+Math.cos(a)*r*unit,cy+Math.sin(a)*r*unit*tilt,1.2,1.2)});
const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,65*zoom);glow.addColorStop(0,'#ffcc60');glow.addColorStop(.25,'#ff9b29aa');glow.addColorStop(1,'#ff9b2900');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,65*zoom,0,7);ctx.fill();ctx.fillStyle='#ffdc85';ctx.beginPath();ctx.arc(cx,cy,13*zoom,0,7);ctx.fill();points=[];
bodies.forEach((body,i)=>{let radius=(i+1.5)*unit,angle=body.phase+days/body.period*Math.PI*2,x=cx+Math.cos(angle)*radius,y=cy+Math.sin(angle)*radius*tilt;const active=body===selected;if(layers.Orbits||track&&active){ctx.strokeStyle=active?'#32bfffaa':'#254b6977';ctx.lineWidth=active?1.2:.7;ctx.beginPath();ctx.ellipse(cx,cy,radius,radius*tilt,0,0,7);ctx.stroke()}let size=([4,7,8,6,16,13,10,10][i])*Math.sqrt(zoom);if(body.name==='Saturn'){ctx.strokeStyle='#d6bc8799';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y,size*1.9,size*.6,.4,0,7);ctx.stroke()}let g=ctx.createRadialGradient(x-size*.4,y-size*.4,0,x,y,size);g.addColorStop(0,'#e6f5ff');g.addColorStop(.35,body.color);g.addColorStop(1,'#091526');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,size,0,7);ctx.fill();if(active){ctx.strokeStyle='#69d9ff';ctx.lineWidth=1;ctx.setLineDash([3,4]);ctx.beginPath();ctx.arc(x,y,size+7,0,7);ctx.stroke();ctx.setLineDash([])}if(layers.Labels){ctx.font='11px Segoe UI';ctx.fillStyle=active?'#bfefff':'#95aec0';ctx.fillText(body.name,x+size+9,y+4)}points.push({x,y,size,body})});$('x').textContent=(selected.au*Math.cos(a)).toFixed(3);$('y').textContent=(selected.au*Math.sin(a)).toFixed(3);$('days').textContent=`T + ${days.toFixed(2)} DAYS`;$('clock').textContent=new Date().toISOString().replace('T',' ').slice(0,19)+' UTC';requestAnimationFrame(frame)}
select(selected);requestAnimationFrame(frame);
